name: Autograde

on:
  push:
    branches: [develop, pytest-integration]
  pull_request:
    branches: [develop, pytest-integration]

jobs:
  run-autograde:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno virtual
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Clonar repositorio de evaluación
      run: git clone https://chucholoport:${{ secrets.AUTOGRADE_PAT }}@github.com/chucholoport/autograde-core.git

    - name: Ejecutar pruebas
      working-directory: autograde-core
      run: pytest ruta/correcta/al/archivo/test_01_intro_numpy.py
