name: Autograde

on:
  push:
    branches: [develop, pytest-integration]
  pull_request:
    branches: [develop, pytest-integration]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run Python scripts
        run: |
          python APRENDIZAJE-AUTOMATICO/intro_libraries/intro_numpy.py
          python APRENDIZAJE-AUTOMATICO/intro_libraries/intro_pandas.py
          python APRENDIZAJE-AUTOMATICO/intro_libraries/intro_scipy.py
          python APRENDIZAJE-AUTOMATICO/intro_libraries/intregrated_exercises.py
